module.exports = {
  /**
   * This method generate standard api response
   * @param {httpRequest} request ,  httpRequest object that is generated by each request from client
   * @param {httpResponse} response,  httpResponse object that is generated by each request from client
   * @param {Object} processedResponse, consist of {code: int of httpStatus code i.e. 200, status: String of httpStatus i.e. 'Created', message: String of message i.e. 'Success login', data: any }
   */
  generateSuccessResponse(request, response, processedResponse) {
    const { timestamp, traceId, headers, body } = request;
    const { code, status, message, data } = processedResponse;
    response.status(code).json({
      timestamp: new Date().toISOString(),
      traceId,
      apiResponse: {
        code,
        status,
        message,
        request: { timestamp, headers, body },
        data
      }
    });
  },
  /**
   * This method generate standard api error response
   * @param {httpRequest} request ,  httpRequest object that is generated by each request from client
   * @param {httpResponse} response,  httpResponse object that is generated by each request from client
   * @param {Object} processedResponse, consist of {code: int of httpStatus code i.e. 200, status: String of httpStatus i.e. 'Created', message: String of message i.e. 'Success login', data: any }
   */
  generateErrorResponse(request, response, processedResponse) {
    const { timestamp, traceId, headers, body } = request;
    const { code, status, message } = processedResponse;
    response.status(code).json({
      timestamp: new Date().toISOString(),
      traceId,
      apiError: {
        code,
        status,
        message,
        request: { timestamp, headers, body }
      }
    });
  }
};
